# remap prefix to Control + Space
set -g prefix C-Space
# bind 'C-Space C-Space' to type 'C-Space'
bind C-Space send-prefix
unbind C-b

setw -g mode-keys vi

# Vi copy mode shortcuts
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi Space send-keys -X clear-selection
bind-key -T copy-mode-vi a send-keys -X append-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -sel clip -i'

# Mouse mode + select copy
set -g mouse on

# Open new panes in the CWD
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Remove date + time from status bar (which gives false indications of changes to terminal output)
set -g status-right '#H'

# More history
set-option -g history-limit 50000

# Do not rename windows. Fixes that windows get renamed even after setting them manually
set-option -g allow-rename off

# Do not exit copy-mode when selecting text
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x

# Workaround for bug where text bleeds from right pane to left
set -ag terminal-overrides ',*:cud1=\E[1B'

# Make OSC 8 hyperlinks work in tmux >= 3.4
if-shell -b '[ "$(echo $TMUX_VERSION >= 3.4" | bc)" = 1 ]' {
    set -as terminal-features ",*:hyperlinks"
}
